name: Test & Upload to TestPyPI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8 

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build setuptools wheel twine
          pip install -r requirements.txt
          
      - name: Build and Upload to TestPyPI
        run: |
          python3 -m build --sdist --wheel .
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
